package model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
@Entity
public class FridgeUser implements Serializable {
	
	/**
	 *  autogenerated ; needed for using serializable
	 */
	private static final long serialVersionUID = 1L;
	
	private String name;
	private String surname;
	private String username;
	private String password;
	private String email;
	public enum Roles { ADMIN, USER; };
	private String role;
	
	// default constructor
	public FridgeUser () {}
	
	public FridgeUser (String name, String surname, String username, String password, String email,String userrole) {
		this.name = name;
		this.surname = surname;
		this.username = username;
		this.password = password;  // Password check?? Bzw. auch 2 pw zur korrekten Eingabe?!
		this.email = email;
		
		if (userrole.equals(Roles.ADMIN))
			this.role = Roles.ADMIN.toString();
		else if (userrole.equals(Roles.USER))
			this.role = Roles.USER.toString();
		else
			System.out.println("The Userrole doesn't match ADMIN or USER!");
		
	}
	

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		if (this.password.equals(password))
				System.out.println("The password can't be the same like the old one!");
		else
			this.password = password;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRole() {
		return role;
	}
	
	@Override
    public String toString() {
        return "User [FirstName=" + this.getSurname()
                + ", lastName=" + this.getName() + ", username=" + this.getUsername()
                + ", email=" + this.getEmail() + ", role=" + this.getRole() + "]";
    }
	
	public void setRole(String role) {
		this.role = role;
	}
}
